version: '3.7'

services:
    kentdb:
        container_name: kentdatabase
        build: ./core
        ports:
            - ${DB_PORT}:5432
        volumes:
            - ./kentdb:/var/lib/kentdb/data
        environment:
            - POSTGRES_DB=kentdb
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
    kentdb:
        external: true
